version: "3.7"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - database:/var/lib/mysql # Use bind mount
      - ../../:/var/www/html:cached

  php:
    image: wodby/drupal-php:$PHP_TAG
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_php"
    environment:
      SSMTP_MAILHUB: mailhog:1025
      PHP_SENDMAIL_PATH: '"/usr/bin/dos2unix -u | /usr/sbin/ssmtp -t -f"'
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      DRUSH_OPTIONS_URI: "https://${PROJECT_BASE_URL}:${PROJECT_PORT}"
      PRODUCTION: 'true'
    volumes:
      - ../../:/var/www/html:cached
#      - /home/ubuntu/.ssh/id_rsa:/home/wodby/.ssh/id_rsa

  crond:
    image: wodby/drupal-php:$PHP_TAG
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E crond -f -d 0
    volumes:
      - ../../:/var/www/html:cached

  nginx:
    image: wodby/nginx:$NGINX_TAG
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - ../../:/var/www/html:cached
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`www.${PROJECT_BASE_URL}`) || Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.middlewares=${PROJECT_NAME}_nginx_non-www_to_www"
      - "traefik.http.middlewares.${PROJECT_NAME}_nginx_non-www_to_www.redirectregex.permanent=true"
      - "traefik.http.middlewares.${PROJECT_NAME}_nginx_non-www_to_www.redirectregex.regex=^https?://(?:www\\.)?(.+)"
      - "traefik.http.middlewares.${PROJECT_NAME}_nginx_non-www_to_www.redirectregex.replacement=https://www.$${1}"
    networks:
      - default
      - traefik

  node:
    image: wodby/node:$NODE_TAG
    container_name: "${PROJECT_NAME}_node"
    working_dir: /var/www/html/web/themes/custom/bancho
    user: root
    volumes:
      - ./../../:/var/www/html
    command: sh -c 'npm install && npm run production'

volumes:
  database:

networks:
  traefik:
    external: true

