<?php

/**
 * @file
 *
 * Contains hooks for bancho_users module.
 */

use Drupal\Core\Url;
use Drupal\image\Entity\ImageStyle;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function bancho_users_theme() {
  return [
    'bancho__user_header_global' => [
      'variables' => [],
    ],
    'bancho__user_header' => [
      'variables' => [],
    ],
    'bancho__user_info' => [
      'variables' => [],
    ],
    'bancho__user_ranking' => [
      'variables' => [],
    ],
    'bancho__user_ranking_chart' => [
      'variables' => [],
    ],
    'bancho__user_ranking_info_under_chart' => [
      'variables' => [],
    ],
    'bancho__user_ranks_count' => [
      'variables' => [],
    ],
    'bancho__user_stats' => [
      'variables' => [],
    ],
    'bancho__user_country' => [
      'variables' => [],
    ],
    'bancho__user_status' => [
      'variables' => [],
    ],
    'bancho__user_menu' => [
      'variables' => [
        'user_id' => NULL,
        'banner' => NULL,
        'avatar' => NULL,
        'username' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess().
 */
function bancho_users_preprocess_user(&$variables, $hook) {
  if ($user = \Drupal::routeMatch()->getParameter('user')) {
    if ($user instanceof UserInterface) {
      $drupal_settings = &$variables['#attached']['drupalSettings']['bancho_users'];
      // @TODO HARDCODED MODE!!!!!!!!!
      $drupal_settings['mode'] = 0;

      // Add profile background if exists.
      if (!($background = $user->get('field_profile_background'))->isEmpty()) {
        $variables['#attached']['library'][] =  'bancho_users/profile-background';
        $drupal_settings['background'] =
          Drupal::service('file_url_generator')
            ->generate($background->entity->getFileUri());
      }

      // Load user info.
      $variables['#attached']['library'][] =  'bancho_users/user-info';
      // Load user status.
      $variables['#attached']['library'][] =  'bancho_users/user-status';

      // @TODO Rework when will be available through localhost.
      // $drupal_settings['data'] =
      // \Drupal::service('bancho_api')->getPlayerInfo($user->id());
    }
  }
}
